// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAfXpxY6DAmoyVL6OAYGhF__etVW2p5bIg',
    appId: '1:988853543636:web:372de469b862b6f22dd141',
    messagingSenderId: '988853543636',
    projectId: 'mlrcc-3206a',
    authDomain: 'mlrcc-3206a.firebaseapp.com',
    storageBucket: 'mlrcc-3206a.appspot.com',
    measurementId: 'G-953RBTP265',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAyuwIM68p2855JaJ9l7E6CGUDKKTmfcIY',
    appId: '1:988853543636:android:ea69d6cd553293502dd141',
    messagingSenderId: '988853543636',
    projectId: 'mlrcc-3206a',
    storageBucket: 'mlrcc-3206a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB43OnoAoZpij_z6_Z7LWMBoIrB6hGRjGs',
    appId: '1:988853543636:ios:58b5a61063a013d92dd141',
    messagingSenderId: '988853543636',
    projectId: 'mlrcc-3206a',
    storageBucket: 'mlrcc-3206a.appspot.com',
    iosClientId: '988853543636-gduf5kbmb7pnbjnq6pqaa2uj95l4mm5h.apps.googleusercontent.com',
    iosBundleId: 'com.lightheads.mlrcc.mlrcc',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB43OnoAoZpij_z6_Z7LWMBoIrB6hGRjGs',
    appId: '1:988853543636:ios:58b5a61063a013d92dd141',
    messagingSenderId: '988853543636',
    projectId: 'mlrcc-3206a',
    storageBucket: 'mlrcc-3206a.appspot.com',
    iosClientId: '988853543636-gduf5kbmb7pnbjnq6pqaa2uj95l4mm5h.apps.googleusercontent.com',
    iosBundleId: 'com.lightheads.mlrcc.mlrcc',
  );
}
